<?php

namespace PollBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends EntityRepository
{
    public function findAllOrderedByQuestion()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PollBundle:Answers p ORDER BY p.question_id ASC')
            ->getResult();
    }
}
