<?php

namespace PollBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{
    public function findAllOrderedByTests()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PollBundle:Questions p ORDER BY p.test_id ASC')
            ->getResult();
    }
}
