<?php

namespace PollBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestsRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PollBundle:Test p ORDER BY p.test_name ASC')
            ->getResult();
    }
}
